# Generated by Django 5.2.1 on 2025-05-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0002_alter_members_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='Member',
        ),
    ]
