# Generated by Django 5.2.1 on 2025-05-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0003_rename_members_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='passwd',
        ),
        migrations.AddField(
            model_name='member',
            name='commit',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='member',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='hfeet',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='member',
            name='hinch',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='signature',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AddField(
            model_name='member',
            name='start',
            field=models.CharField(default='Immediately', max_length=25),
        ),
        migrations.AddField(
            model_name='member',
            name='stuck',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='member',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='fname',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='lname',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
