# Generated by Django 5.2.1 on 2025-05-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0004_remove_member_passwd_member_commit_member_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='hfeet',
        ),
        migrations.RemoveField(
            model_name='member',
            name='hinch',
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.CharField(default='None', max_length=5),
        ),
    ]
