# Generated by Django 5.2.1 on 2025-05-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0005_remove_member_hfeet_remove_member_hinch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
