# Generated by Django 5.2.1 on 2025-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0006_alter_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='signup',
            field=models.BooleanField(default='False'),
        ),
    ]
