# Generated by Django 5.2.1 on 2025-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0007_member_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='signup',
            field=models.BooleanField(default=False),
        ),
    ]
