# Generated by Django 5.2.1 on 2025-05-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0008_alter_member_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='goal',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='height',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
