# Generated by Django 5.2.1 on 2025-06-02 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0009_alter_member_goal_alter_member_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
