# Generated by Django 5.2.4 on 2025-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0010_member_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='stuck',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
