# Generated by Django 5.2.5 on 2025-08-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sends', '0011_alter_member_stuck'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hasJob',
            field=models.CharField(default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='member',
            name='monthlyIncome',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
    ]
